version: '3'
services:     
  db:
    build:
      context: .
      dockerfile: ./Dockerfile.db
    restart: always
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Supersecur3!
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: ./Dockerfile.api
    command: Server=db;Database=BOUNTY;Trusted_Connection=True;MultipleActiveResultSets=True
    ports:
      - '80:80'
    depends_on:
      - db

volumes:
  sql_data:
